name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test GitVersion
      shell: pwsh
      run: ls $pwd; dotnet-gitversion
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap

