name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test GitVersion
      shell: pwsh
      run: ls $pwd; dotnet-gitversion
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
  publish:
    name: Run build
    needs:
      - test
    if: ${{success()}}
    runs-on: windows-latest
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: publish
      shell: pwsh
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      run: $env:PSGALLERY_API_KEY ; ./build.ps1 -Task Publish -Bootstrap
